version: '3.0'

services:
  backend:
    container_name: backend
    build:
      context: .
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3001:3001
    depends_on:
      - postgres
    volumes:
      - .:/app
      - .:/node_modules

  postgres:
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    image: postgres:13.3
    environment:
      PG_DATA: /var/lib/postgres/data
